# Generated by Django 4.1 on 2022-08-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='total',
            field=models.IntegerField(),
        ),
    ]
