# Generated by Django 4.1 on 2022-08-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_description_product_definition_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/empty.webp', upload_to='category'),
        ),
    ]
